<a href="https://colab.research.google.com/github/jyothika5968/Machine_Learning/blob/main/Forecasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/AirPassengers.csv')
df.head(5)

     Month  #Passengers
0  1949-01          112
1  1949-02          118
2  1949-03          132
3  1949-04          129
4  1949-05          121

In [ ]:
df.tail(5)

       Month  #Passengers
139  1960-08          606
140  1960-09          508
141  1960-10          461
142  1960-11          390
143  1960-12          432

In [ ]:
# Rename
df.rename(columns={'Month':'ds','#Passengers':'y'},inplace=True)
df.head(5)

        ds    y
0  1949-01  112
1  1949-02  118
2  1949-03  132
3  1949-04  129
4  1949-05  121

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ds      144 non-null    object
 1   y       144 non-null    int64
dtypes: int64(1), object(1)
memory usage: 2.4+ KB

In [ ]:
# x convert it into date object
df['ds']=pd.to_datetime(df['ds'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ds      144 non-null    datetime64[ns]
 1   y       144 non-null    int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 2.4 KB

In [ ]:
df

            ds    y
0   1949-01-01  112
1   1949-02-01  118
2   1949-03-01  132
3   1949-04-01  129
4   1949-05-01  121
..         ...  ...
139 1960-08-01  606
140 1960-09-01  508
141 1960-10-01  461
142 1960-11-01  390
143 1960-12-01  432

[144 rows x 2 columns]

In [ ]:
# fit the prophet model
from prophet import Prophet
model=Prophet()
model.fit(df)

INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.